/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDoctorsRouteImport } from './routes/app.doctors'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppDoctorScheduleRouteImport } from './routes/app.doctor.schedule'
import { Route as AppDoctorProfileRouteImport } from './routes/app.doctor.profile'
import { Route as AppDoctorAppointmentsRouteImport } from './routes/app.doctor.appointments'
import { Route as AppConsultIdRouteImport } from './routes/app.consult.$id'
import { Route as AppBookDoctorIdRouteImport } from './routes/app.book.$doctorId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/app/records',
  path: '/app/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/app/doctors',
  path: '/app/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/app/appointments',
  path: '/app/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/app/ai',
  path: '/app/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDoctorScheduleRoute = AppDoctorScheduleRouteImport.update({
  id: '/app/doctor/schedule',
  path: '/app/doctor/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDoctorProfileRoute = AppDoctorProfileRouteImport.update({
  id: '/app/doctor/profile',
  path: '/app/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDoctorAppointmentsRoute = AppDoctorAppointmentsRouteImport.update({
  id: '/app/doctor/appointments',
  path: '/app/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConsultIdRoute = AppConsultIdRouteImport.update({
  id: '/app/consult/$id',
  path: '/app/consult/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookDoctorIdRoute = AppBookDoctorIdRouteImport.update({
  id: '/app/book/$doctorId',
  path: '/app/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/': typeof AppIndexRoute
  '/app/book/$doctorId': typeof AppBookDoctorIdRoute
  '/app/consult/$id': typeof AppConsultIdRoute
  '/app/doctor/appointments': typeof AppDoctorAppointmentsRoute
  '/app/doctor/profile': typeof AppDoctorProfileRoute
  '/app/doctor/schedule': typeof AppDoctorScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app': typeof AppIndexRoute
  '/app/book/$doctorId': typeof AppBookDoctorIdRoute
  '/app/consult/$id': typeof AppConsultIdRoute
  '/app/doctor/appointments': typeof AppDoctorAppointmentsRoute
  '/app/doctor/profile': typeof AppDoctorProfileRoute
  '/app/doctor/schedule': typeof AppDoctorScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/': typeof AppIndexRoute
  '/app/book/$doctorId': typeof AppBookDoctorIdRoute
  '/app/consult/$id': typeof AppConsultIdRoute
  '/app/doctor/appointments': typeof AppDoctorAppointmentsRoute
  '/app/doctor/profile': typeof AppDoctorProfileRoute
  '/app/doctor/schedule': typeof AppDoctorScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/appointments'
    | '/app/doctors'
    | '/app/profile'
    | '/app/records'
    | '/app/'
    | '/app/book/$doctorId'
    | '/app/consult/$id'
    | '/app/doctor/appointments'
    | '/app/doctor/profile'
    | '/app/doctor/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/appointments'
    | '/app/doctors'
    | '/app/profile'
    | '/app/records'
    | '/app'
    | '/app/book/$doctorId'
    | '/app/consult/$id'
    | '/app/doctor/appointments'
    | '/app/doctor/profile'
    | '/app/doctor/schedule'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/appointments'
    | '/app/doctors'
    | '/app/profile'
    | '/app/records'
    | '/app/'
    | '/app/book/$doctorId'
    | '/app/consult/$id'
    | '/app/doctor/appointments'
    | '/app/doctor/profile'
    | '/app/doctor/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AppAiRoute: typeof AppAiRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookDoctorIdRoute: typeof AppBookDoctorIdRoute
  AppConsultIdRoute: typeof AppConsultIdRoute
  AppDoctorAppointmentsRoute: typeof AppDoctorAppointmentsRoute
  AppDoctorProfileRoute: typeof AppDoctorProfileRoute
  AppDoctorScheduleRoute: typeof AppDoctorScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/records': {
      id: '/app/records'
      path: '/app/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/doctors': {
      id: '/app/doctors'
      path: '/app/doctors'
      fullPath: '/app/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/app/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/app/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/doctor/schedule': {
      id: '/app/doctor/schedule'
      path: '/app/doctor/schedule'
      fullPath: '/app/doctor/schedule'
      preLoaderRoute: typeof AppDoctorScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/doctor/profile': {
      id: '/app/doctor/profile'
      path: '/app/doctor/profile'
      fullPath: '/app/doctor/profile'
      preLoaderRoute: typeof AppDoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/doctor/appointments': {
      id: '/app/doctor/appointments'
      path: '/app/doctor/appointments'
      fullPath: '/app/doctor/appointments'
      preLoaderRoute: typeof AppDoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/consult/$id': {
      id: '/app/consult/$id'
      path: '/app/consult/$id'
      fullPath: '/app/consult/$id'
      preLoaderRoute: typeof AppConsultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book/$doctorId': {
      id: '/app/book/$doctorId'
      path: '/app/book/$doctorId'
      fullPath: '/app/book/$doctorId'
      preLoaderRoute: typeof AppBookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AppAiRoute: AppAiRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookDoctorIdRoute: AppBookDoctorIdRoute,
  AppConsultIdRoute: AppConsultIdRoute,
  AppDoctorAppointmentsRoute: AppDoctorAppointmentsRoute,
  AppDoctorProfileRoute: AppDoctorProfileRoute,
  AppDoctorScheduleRoute: AppDoctorScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
